# Generated by Django 2.0.1 on 2018-01-22 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='City name')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.PositiveSmallIntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('types', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cuisine', models.CharField(max_length=50)),
                ('rate', models.PositiveSmallIntegerField()),
                ('website', models.URLField(max_length=100)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(default='000-000-0000', max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.City')),
            ],
        ),
        migrations.CreateModel(
            name='StateOrProvince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='resturant',
            name='stateorprovince',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.StateOrProvince'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menusection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.MenuSection'),
        ),
        migrations.AddField(
            model_name='menu',
            name='resturant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Resturant'),
        ),
    ]
